'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { Bell, Bot, Building2, ChevronLeft, ChevronRight, DollarSign, FileText, Fuel, LayoutDashboard, LogOut, Menu, Plus, Route, Search, Settings, ShieldAlert, ShieldCheck, Smartphone, Truck, UserCheck, Users, Wrench } from 'lucide-react';
import { useApp } from '@/context/AppContext';
import { CommandPalette } from './CommandPalette';
import { NotificationsPanel } from './NotificationsPanel';
import { Button } from '@/components/ui';

const getInitials = (name?: string) => { if (!name) return 'TS'; const parts = name.trim().split(/\s+/); return parts.length === 1 ? parts[0].slice(0, 2).toUpperCase() : `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase(); };

const sections = [
  { title: 'Operations', items: [{ name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard }, { name: 'Trips & Dispatch', href: '/trips', icon: Route }, { name: 'AI Smart Dispatch', href: '/ai-dispatch', icon: Bot }] },
  { title: 'Fleet', items: [{ name: 'Vehicles', href: '/vehicles', icon: Truck }, { name: 'Drivers', href: '/drivers', icon: UserCheck }, { name: 'Predictive Maintenance', href: '/maintenance', icon: Wrench }, { name: 'Fuel Telemetry', href: '/fuel', icon: Fuel }] },
  { title: 'Finance & Safety', items: [{ name: 'Trip Expenses & P&L', href: '/expenses', icon: DollarSign }, { name: 'AI Safety Center', href: '/safety', icon: ShieldAlert }, { name: 'Reports & Exports', href: '/reports', icon: FileText }] },
  { title: 'Admin', items: [{ name: 'Company Profile', href: '/company', icon: Building2 }, { name: 'User Management', href: '/users', icon: Users }, { name: 'Roles & Permissions', href: '/roles', icon: ShieldCheck }, { name: 'System Settings', href: '/settings', icon: Settings }] }
];

export const Sidebar: React.FC<{ collapsed: boolean; setCollapsed: (value: boolean) => void }> = ({ collapsed, setCollapsed }) => {
  const pathname = usePathname(); const router = useRouter(); const { currentUser, signOut } = useApp(); const isDriver = currentUser?.role === 'Driver';
  const handleLogout = async () => { await signOut(); router.push('/login'); };
  const visibleSections = isDriver ? [{ title: 'Driver operations', items: [{ name: 'Driver Field Portal', href: '/driver-portal', icon: Smartphone }] }] : sections;
  return <aside className={`fixed inset-y-0 left-0 z-50 flex flex-col border-r border-white/10 bg-brand-navy text-white transition-[width] duration-150 ${collapsed ? 'w-16' : 'w-60'}`}>
    <div className="flex h-14 items-center justify-between border-b border-white/10 px-3"><Link href={isDriver ? '/driver-portal' : '/dashboard'} className="flex min-w-0 items-center gap-2"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-control bg-white"><img src="/logo-dark.png" alt="TruckSaathi" className="h-5 w-5 object-contain" /></div>{!collapsed && <span className="truncate text-sm font-bold">TruckSaathi</span>}</Link><button onClick={() => setCollapsed(!collapsed)} className="rounded-control p-1.5 text-white/70 hover:bg-white/10 hover:text-white" aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{collapsed ? <ChevronRight className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}</button></div>
    <nav className="flex-1 space-y-5 overflow-y-auto px-2 py-5">{visibleSections.map(section => <div key={section.title}><div className={`mb-2 px-2 text-xs font-semibold text-white/50 ${collapsed ? 'sr-only' : ''}`}>{section.title}</div>{section.items.map(item => { const active = pathname === item.href || (item.href !== '/dashboard' && pathname?.startsWith(item.href)); const Icon = item.icon; return <Link key={item.href} href={item.href} title={collapsed ? item.name : undefined} className={`relative mb-1 flex h-9 items-center gap-3 rounded-control px-2.5 text-sm transition-colors duration-150 ${active ? 'bg-brand-orange/20 text-white' : 'text-white/75 hover:bg-white/10 hover:text-white'}`}>{active && <span className="absolute left-0 top-1 bottom-1 w-1 rounded-r bg-brand-orange" />}<Icon className="h-4 w-4 shrink-0" />{!collapsed && <span className="truncate">{item.name}</span>}</Link>; })}</div>)}</nav>
    <div className="border-t border-white/10 p-3"><div className={`flex items-center gap-2 ${collapsed ? 'justify-center' : ''}`}><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white/15 text-xs font-bold">{getInitials(currentUser?.name)}</div>{!collapsed && <div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{currentUser?.name || 'Fleet operator'}</p><p className="truncate text-xs text-white/60">{currentUser?.role || 'Admin'}</p></div>}{!collapsed && <button onClick={handleLogout} className="rounded-control p-1.5 text-white/60 hover:bg-white/10 hover:text-white" title="Log out" aria-label="Log out"><LogOut className="h-4 w-4" /></button>}</div></div>
  </aside>;
};

const pageTitles: Record<string, string> = { '/dashboard': 'Dashboard', '/trips': 'Trips & Dispatch', '/ai-dispatch': 'AI Smart Dispatch', '/vehicles': 'Vehicles', '/drivers': 'Drivers', '/maintenance': 'Predictive Maintenance', '/fuel': 'Fuel Telemetry', '/expenses': 'Trip Expenses & P&L', '/safety': 'AI Safety Center', '/reports': 'Reports & Exports', '/company': 'Company Profile', '/users': 'User Management', '/roles': 'Roles & Permissions', '/settings': 'System Settings', '/driver-portal': 'Driver Field Portal' };

export const Header: React.FC<{ collapsed: boolean }> = ({ collapsed }) => {
  const pathname = usePathname(); const router = useRouter(); const { currentUser, signOut } = useApp(); const [commandOpen, setCommandOpen] = useState(false); const [notificationsOpen, setNotificationsOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen(value => !value); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  const title = pageTitles[pathname || ''] || 'Control tower';
  const handleLogout = async () => { await signOut(); router.push('/login'); };
  return <><header className={`sticky top-0 z-40 flex h-14 items-center justify-between border-b border-border bg-surface px-4 transition-[margin] duration-150 sm:px-6 ${collapsed ? 'ml-16' : 'ml-60'}`}><div className="flex min-w-0 items-center gap-3"><Menu className="h-4 w-4 text-text-muted lg:hidden" /><div className="min-w-0"><p className="truncate text-sm font-semibold text-text-primary">{title}</p><p className="hidden text-xs text-text-muted sm:block">TruckSaathi / {title}</p></div></div><div className="hidden w-full max-w-sm md:block"><button onClick={() => setCommandOpen(true)} className={`flex w-full items-center gap-2 rounded-control border border-border bg-surface-muted px-3 py-2 text-left text-sm text-text-muted ${focusRing}`}><Search className="h-4 w-4" /><span className="flex-1">Search vehicles, drivers, trips</span><kbd className="rounded border border-border bg-surface px-1.5 py-0.5 text-xs">Ctrl K</kbd></button></div><div className="flex items-center gap-2"><Button variant="ghost" size="sm" icon={<Bot className="h-4 w-4" />} className="hidden sm:inline-flex" onClick={() => router.push('/ai-dispatch')}>Ask AI</Button>{!currentUser || currentUser.role === 'Driver' ? null : <Link href="/trips" className="hidden sm:inline-flex"><Button size="sm" icon={<Plus className="h-4 w-4" />}>New dispatch</Button></Link>}<button onClick={() => setNotificationsOpen(true)} className="relative rounded-control p-2 text-text-secondary hover:bg-surface-muted" aria-label="Notifications"><Bell className="h-4 w-4" /><span className="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-brand-orange" /></button><div className="relative"><button onClick={() => setProfileOpen(value => !value)} className="flex items-center gap-2 rounded-control p-1.5 hover:bg-surface-muted" aria-label="Open profile menu"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-brand-navy text-xs font-semibold text-white">{getInitials(currentUser?.name)}</span><span className="hidden max-w-28 truncate text-xs font-semibold text-text-primary lg:block">{currentUser?.name || 'Fleet operator'}</span></button>{profileOpen && <div className="absolute right-0 top-10 z-50 w-44 rounded-card border border-border bg-surface p-1 shadow-popover"><Link href="/settings" onClick={() => setProfileOpen(false)} className="block rounded-control px-3 py-2 text-sm text-text-secondary hover:bg-surface-muted">System settings</Link><button onClick={handleLogout} className="block w-full rounded-control px-3 py-2 text-left text-sm text-text-secondary hover:bg-surface-muted">Log out</button></div>}</div></div></header><CommandPalette isOpen={commandOpen} onClose={() => setCommandOpen(false)} /><NotificationsPanel isOpen={notificationsOpen} onClose={() => setNotificationsOpen(false)} /></>;
};

export const LayoutShell: React.FC<{ children: React.ReactNode }> = ({ children }) => { const [collapsed, setCollapsed] = useState(false); return <div className="min-h-screen bg-canvas text-text-primary"><Sidebar collapsed={collapsed} setCollapsed={setCollapsed} /><Header collapsed={collapsed} /><main className={`min-h-[calc(100vh-56px)] p-4 transition-[margin] duration-150 sm:p-6 ${collapsed ? 'ml-16' : 'ml-60'}`}><div className="mx-auto w-full max-w-[1440px] space-y-6">{children}</div></main></div>; };

const focusRing = 'focus:outline-none focus-visible:ring-2 focus-visible:ring-focus';