'use client';

import React, { useEffect } from 'react';
import { ArrowDown, ArrowUp, Loader2, X } from 'lucide-react';
import { motion, useReducedMotion } from 'framer-motion';

const focusRing = 'focus:outline-none focus-visible:ring-2 focus-visible:ring-focus focus-visible:ring-offset-2 focus-visible:ring-offset-surface';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger' | 'amber';
  size?: 'sm' | 'md' | 'lg';
  icon?: React.ReactNode;
  loading?: boolean;
}

export const Button: React.FC<ButtonProps> = ({ children, variant = 'primary', size = 'md', icon, loading = false, disabled, className = '', ...props }) => {
  const variants = { primary: 'bg-brand-orange text-white hover:bg-orange-700 border-brand-orange', secondary: 'bg-surface-muted text-text-primary hover:bg-slate-200 border-border', outline: 'bg-transparent text-text-primary hover:bg-surface-muted border-border', ghost: 'bg-transparent text-text-secondary hover:bg-surface-muted border-transparent', danger: 'bg-red-600 text-white hover:bg-red-700 border-red-600', amber: 'bg-brand-orange text-white hover:bg-orange-700 border-brand-orange' };
  const sizes = { sm: 'min-h-8 px-3 text-xs gap-1.5', md: 'min-h-9 px-4 text-sm gap-2', lg: 'min-h-11 px-5 text-sm gap-2.5' };
  return <button disabled={disabled || loading} className={`inline-flex items-center justify-center rounded-control border font-semibold transition-colors duration-150 disabled:cursor-not-allowed disabled:opacity-50 ${focusRing} ${variants[variant]} ${sizes[size]} ${className}`} {...props}>{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : icon ? <span className="shrink-0">{icon}</span> : null}<span>{children}</span></button>;
};

export const Card: React.FC<{ children: React.ReactNode; className?: string; onClick?: () => void; glow?: string; tilt?: boolean }> = ({ children, className = '', onClick }) => <div onClick={onClick} className={`rounded-card border border-border bg-surface p-5 ${onClick ? 'cursor-pointer hover:border-slate-300' : ''} ${className}`}>{children}</div>;

type StatusVariant = 'success' | 'warning' | 'danger' | 'info' | 'cyan' | 'neutral' | 'maintenance' | 'vibe';
const statusStyles: Record<StatusVariant, string> = { success: 'bg-green-50 text-green-800 border-green-200', warning: 'bg-amber-50 text-amber-800 border-amber-200', danger: 'bg-red-50 text-red-800 border-red-200', info: 'bg-blue-50 text-blue-800 border-blue-200', cyan: 'bg-blue-50 text-blue-800 border-blue-200', neutral: 'bg-slate-100 text-slate-700 border-slate-200', maintenance: 'bg-violet-50 text-violet-800 border-violet-200', vibe: 'bg-orange-50 text-orange-800 border-orange-200' };
const statusDots: Record<StatusVariant, string> = { success: 'bg-green-600', warning: 'bg-amber-600', danger: 'bg-red-600', info: 'bg-blue-600', cyan: 'bg-blue-600', neutral: 'bg-slate-500', maintenance: 'bg-violet-600', vibe: 'bg-orange-600' };
export const StatusPill: React.FC<{ children: React.ReactNode; status?: StatusVariant; variant?: StatusVariant; className?: string }> = ({ children, status = 'neutral', variant, className = '' }) => { const resolved = variant || status; return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-semibold ${statusStyles[resolved]} ${className}`}><span className={`h-1.5 w-1.5 rounded-full ${statusDots[resolved]}`} />{children}</span>; };
export const Badge: React.FC<{ children: React.ReactNode; variant?: StatusVariant; pulse?: boolean; className?: string }> = ({ children, variant = 'neutral', className = '' }) => <StatusPill status={variant} className={className}>{children}</StatusPill>;

export const Input: React.FC<React.InputHTMLAttributes<HTMLInputElement> & { icon?: React.ReactNode }> = ({ icon, className = '', ...props }) => <div className="relative w-full">{icon && <span className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted">{icon}</span>}<input className={`w-full rounded-control border border-border bg-surface px-3 py-2 text-sm text-text-primary placeholder:text-text-muted ${icon ? 'pl-9' : ''} ${focusRing} ${className}`} {...props} /></div>;
export const Select: React.FC<React.SelectHTMLAttributes<HTMLSelectElement>> = ({ className = '', ...props }) => <select className={`w-full rounded-control border border-border bg-surface px-3 py-2 text-sm text-text-primary ${focusRing} ${className}`} {...props} />;
export const Textarea: React.FC<React.TextareaHTMLAttributes<HTMLTextAreaElement>> = ({ className = '', ...props }) => <textarea className={`w-full rounded-control border border-border bg-surface px-3 py-2 text-sm text-text-primary placeholder:text-text-muted ${focusRing} ${className}`} {...props} />;

export const Table: React.FC<React.TableHTMLAttributes<HTMLTableElement>> = ({ className = '', ...props }) => <div className="overflow-x-auto rounded-card border border-border"><table className={`w-full border-collapse text-left text-[13px] ${className}`} {...props} /></div>;
export const TableHeader: React.FC<React.HTMLAttributes<HTMLTableSectionElement>> = ({ className = '', ...props }) => <thead className={`sticky top-0 bg-surface-muted text-xs font-semibold text-text-secondary ${className}`} {...props} />;
export const TableBody: React.FC<React.HTMLAttributes<HTMLTableSectionElement>> = ({ className = '', ...props }) => <tbody className={`divide-y divide-border ${className}`} {...props} />;
export const TableRow: React.FC<React.HTMLAttributes<HTMLTableRowElement>> = ({ className = '', ...props }) => <tr className={`h-11 transition-colors duration-150 hover:bg-surface-muted ${className}`} {...props} />;
export const TableHead: React.FC<React.ThHTMLAttributes<HTMLTableCellElement>> = ({ className = '', ...props }) => <th className={`px-4 py-3 text-left ${className}`} {...props} />;
export const TableCell: React.FC<React.TdHTMLAttributes<HTMLTableCellElement>> = ({ className = '', ...props }) => <td className={`px-4 py-3 text-text-primary ${className}`} {...props} />;

export const PageHeader: React.FC<{ title: string; description?: string; subtitle?: string; badge?: React.ReactNode; actions?: React.ReactNode }> = ({ title, description, subtitle, badge, actions }) => <div className="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-brand-navy dark:text-text-primary">{title}</h1>{badge}</div>{(description || subtitle) && <p className="mt-1 max-w-2xl text-sm text-text-secondary">{description || subtitle}</p>}</div>{actions && <div className="flex shrink-0 items-center gap-2">{actions}</div>}</div>;
export const AnimatedNumber: React.FC<{ value: number }> = ({ value }) => <span className="tabular-nums font-semibold">{value}</span>;

interface KpiProps { title?: string; label?: string; value?: string | number; number?: string | number; subtext?: string; delta?: string; trend?: { direction?: 'up' | 'down'; isPositive?: boolean; value: string }; icon?: React.ReactNode; iconBg?: string; glow?: string; sparkline?: React.ReactNode; }
export const KpiCard: React.FC<KpiProps> = ({ title, label, value, number, subtext, delta, trend, icon, sparkline }) => { const change = delta || trend?.value; const positive = trend?.isPositive ?? (trend?.direction ? trend.direction === 'up' : true); return <Card className="flex min-h-32 flex-col justify-between"><div className="flex items-start justify-between gap-3"><span className="text-xs font-semibold text-text-secondary">{label || title}</span>{icon && <span className="text-brand-orange">{icon}</span>}</div><div className="mt-3 flex items-end justify-between gap-3"><span className="text-2xl font-bold tabular-nums text-text-primary">{number ?? value}</span>{change && <span className={`inline-flex items-center gap-1 text-xs font-semibold ${positive ? 'text-green-700' : 'text-red-700'}`}>{positive ? <ArrowUp className="h-3.5 w-3.5" /> : <ArrowDown className="h-3.5 w-3.5" />}{change}</span>}{sparkline}</div>{subtext && <span className="mt-2 text-xs text-text-muted">{subtext}</span>}</Card>; };
export const KPICard: React.FC<KpiProps> = props => <KpiCard {...props} />;

export const Modal: React.FC<{ isOpen: boolean; onClose: () => void; title: string; description?: string; children: React.ReactNode; size?: 'sm' | 'md' | 'lg' | 'xl' | string; maxWidth?: string }> = ({ isOpen, onClose, title, description, children, size = 'lg', maxWidth }) => { useEffect(() => { const key = (event: KeyboardEvent) => event.key === 'Escape' && onClose(); if (isOpen) { document.body.style.overflow = 'hidden'; window.addEventListener('keydown', key); } return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', key); }; }, [isOpen, onClose]); if (!isOpen) return null; const sizes: Record<string, string> = { sm: 'max-w-md', md: 'max-w-lg', lg: 'max-w-2xl', xl: 'max-w-4xl' }; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><button className="absolute inset-0 cursor-default" aria-label="Close modal" onClick={onClose} /><div className={`relative z-10 w-full rounded-card border border-border bg-surface p-6 shadow-popover ${maxWidth || sizes[size] || sizes.lg}`}><div className="mb-5 flex items-start justify-between border-b border-border pb-4"><div><h2 className="text-lg font-bold text-text-primary">{title}</h2>{description && <p className="mt-1 text-sm text-text-secondary">{description}</p>}</div><button onClick={onClose} className={`rounded-control p-1 text-text-secondary hover:bg-surface-muted ${focusRing}`} aria-label="Close"><X className="h-4 w-4" /></button></div><div className="max-h-[75vh] overflow-y-auto">{children}</div></div></div>; };
export const Drawer: React.FC<{ isOpen: boolean; onClose: () => void; title: string; children: React.ReactNode }> = ({ isOpen, onClose, title, children }) => !isOpen ? null : <div className="fixed inset-0 z-50 bg-black/40"><button className="absolute inset-0" aria-label="Close drawer" onClick={onClose} /><aside className="absolute right-0 top-0 h-full w-full max-w-lg overflow-y-auto border-l border-border bg-surface p-6 shadow-popover"><div className="mb-6 flex items-center justify-between border-b border-border pb-4"><h2 className="text-lg font-bold text-text-primary">{title}</h2><button onClick={onClose} className={`rounded-control p-1 text-text-secondary hover:bg-surface-muted ${focusRing}`} aria-label="Close"><X className="h-4 w-4" /></button></div>{children}</aside></div>;
export const EmptyState: React.FC<{ icon: React.ReactNode; title: string; description: string; action?: React.ReactNode }> = ({ icon, title, description, action }) => <div className="flex flex-col items-center justify-center gap-3 rounded-card border border-dashed border-border p-10 text-center"><div className="text-brand-orange">{icon}</div><h3 className="text-sm font-semibold text-text-primary">{title}</h3><p className="max-w-sm text-sm text-text-secondary">{description}</p>{action}</div>;
export const Skeleton: React.FC<{ className?: string }> = ({ className = '' }) => <div className={`rounded-control bg-surface-muted ${className}`} aria-hidden="true" />;
export const itemVariants = { hidden: { opacity: 0, y: 8 }, visible: { opacity: 1, y: 0, transition: { duration: 0.15 } } };
export const RouteDivider: React.FC<{ className?: string }> = ({ className = '' }) => <div className={`route-line-divider my-4 ${className}`} />;
export const AnimatedPage: React.FC<{ children: React.ReactNode }> = ({ children }) => { const reduce = useReducedMotion(); return <motion.div initial={reduce ? false : { opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.15 }} className="space-y-6">{children}</motion.div>; };